resources:
  - name: be_gitRepo
    type: GitRepo
    configuration:
      path: RjSH1/project-examples
      gitProvider: zenGit
 
  - name: appl_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: zenArt
      
  - name: appl_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: zenArt
pipelines:
  - name: demo_application
    steps:
      - name: bld_backend
        type: MvnBuild
        configuration:
          inputResources:
            - name: be_gitRepo
          integrations:
            - name: zenArt
