resources:
  - name: be_gitRepo
    type: GitRepo
    configuration:
      path: RjSH1/project-examples
      gitProvider: zenGit
 
  - name: appl_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: zenArt
      
  - name: appl_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: zenArt
      
pipelines:
  - name: demo_application
        configuration:
          environmentVariables:
            readOnly:
              JFROG_CLI_BUILD_NAME: backend_build

    steps:
      - name: bld_backend
        type: MvnBuild
        configuration:
          sourceLocation: .
          mvnCommand: clean install -ntp
          inputResources:
            - name: be_gitRepo
          integrations:
            - name: zenArt
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
        execution:
          onStart:
            - javac -version
            - mvn --version
